### ISSUE TITLE
Error in nlsModel(formula, mf, start, wts) : singular gradient matrix at initial parameter estimates

### ISSUE THREAD

**Issue by Wenhui-bio** [RWParsons/circacompare#4] opened 2022-12-06 14:18 UTC
Hi, while using this tool, I encountered a problem.
I have a rhythm gene expressed as like this: 
![image](https://user-images.githubusercontent.com/34473055/205934396-dd1fb09e-c992-4cac-98ef-c856b358f352.png)
This command, `circa_single(x=data_single, col_time="time", col_outcome="measure", period=24)`, can be performed successfully. 

However, sometimes we need to scale these expression. 
![image](https://user-images.githubusercontent.com/34473055/205935555-a1979875-f6f8-433d-882c-fbc983e36392.png)
now, if I performed that command using scaled expression `scale(data_single$measure)`, I would got a error `Error in nlsModel(formula, mf, start, wts) : singular gradient matrix at initial parameter estimates`
What is this error meaning? How can I do now?

**Comment by RWParsons** [comment] 2022-12-07 23:59
Hi whui,

Could you please provide a reproducible example that I could use to recreate the error?
What version of circacompare are you using?
Does the model eventually fit and return a circacompare object or does it time out eventually?

Do you need to scale the data? Note that if you scale the data, the interpretation of the mesor and amplitude is impossible. It will mean that you can only interpret phase, which will be estimated the same if you were to have not scaled the data anyway.

Cheers,
Rex

**Comment by Wenhui-bio** [comment] 2022-12-08 01:57
I am very pleased to receive your reply!
When I used the scaled data from https://cran.r-project.org/web/packages/circacompare/vignettes/circacompare-vignette.html, that error also occurred.
```
data_single <- make_data(k1=0, alpha1=0, phi1=0, noise_sd=1)[c("time", "measure")]
result <- circa_single(x=data_single, col_time="time", col_outcome="measure", period=24) #can be performed successfully

data_single2 <- data.frame(time=data_single$time, measure=scale(data_single$measure))
result <- circa_single(x=data_single2, col_time="time", col_outcome="measure", period=24)#a error mentioned above was occured
```

circacompare version: 0.1.1

about the last question, 'Do you need to scale the data?', I think yes. If you have a expression module containing so many genes, with a similar pattern. and you want to check the rhythmic about the module. What will you do？(Hope to get your advice)
'It will mean that you can only interpret phase', yes, we mainly focus on phase changes

**Comment by RWParsons** [comment] 2022-12-09 06:05
Thanks for the reponse and example. I can see the problem but I think this problem is inherent when using these data and nls to fit the model. I would also note that since you're scaling the data, the mesor parameter is always going to be zero. 

If you're wanting to assess rhythmicity, I would consider a different algorithm altogether - something like JTK cycle is better suited to this than circacompare (which was never intended to be used as a method to assess the presence of rhythmicity).

If you want to use a cosinor model to assess this still, then I would use the linearised form (try the cosinor and cosinor2 R packages). If you're scaling the data, you may want to remove the intercept term as well but I'm not sure if this is possible with these packages.

I'm going to close this issue but please contact me if I can be of any other help.

**Closed as completed by RWParsons** 2022-12-09 06:05 UTC

**Comment by Wenhui-bio** [comment] 2022-12-09 06:17
Ok, thank you very much for your advices！
Best wishes
